GET http://localhost:3000/me
Authorization: Babeir eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTU2MTc4MiwiZXhwIjoxNjg1NTYyNjgyfQ.Zf1p9k5LpsE26u2bKTzsYJf09rVp20cuFutSf2FeRMk
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTU2MTA0MCwiZXhwIjoxNjg2MTY1ODQwfQ.tLAhqaLJ3X4T4J97i_to3QslchgRvyhOt4betuR-VXA"
}

###Login Route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "tnowad@gmail.com",
  "password": "password"
}

###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "tnowad@gmail.com",
  "password": "password",
  "name": "Nguyen Minh Tuan"
}

###Refresh token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTU2MTA0MCwiZXhwIjoxNjg2MTY1ODQwfQ.tLAhqaLJ3X4T4J97i_to3QslchgRvyhOt4betuR-VXA"
}

###Logout Route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NTU2MTA0MCwiZXhwIjoxNjg2MTY1ODQwfQ.tLAhqaLJ3X4T4J97i_to3QslchgRvyhOt4betuR-VXA"
}
